import { type NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Test: NextPage = () => {
  const { data } = trpc.mail.test.useQuery();

  return (
    <>
      <Head>
        <title>mailr | Test</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white">{JSON.stringify(data)}</div>
      </main>
    </>
  );
};

export default Test;
